# This is a basic workflow to help you get started with Actions
name: Deploy api to Heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [published]
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    name: Test, Build and Deploy to Production
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Show release Version
        run: echo ${{ github.event.release.tag_name }}
      #- name: Get Node_Modules cache directory
      #  id: npm-cache
      #  run: |
      #    echo "::set-output name=dir::$(npm config get cache)"
      #- uses: actions/cache@v2
      #  with:
      #    path: ${{ steps.npm-cache.outputs.dir }}
      #    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #    restore-keys: |
      #      ${{ runner.os }}-node-
      #- name: upgrade npm
      #  run: npm install -g npm
      #- name: Install dependencies
      #  run: npm install
      #- name: Run test pre build
      #  run: npm run test
      #- name: Run Build
      #  run: npm run build
      #- name: Deploy to Heroku
      #  uses: akhileshns/heroku-deploy@v3.8.9
      #  with:
      #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #    heroku_app_name: "api-ms-vuttr"
      #    heroku_email: ${{secrets.HEROKU_EMAIL}}